apiVersion: v1
kind: PersistentVolume
metadata: 
  name: vishal-pv
spec:
  accessModes:
  -  ReadWriteMany
  capacity:
    storage: 4Gi
  azureFile:
    shareName: vishalfileshare
    secretName: azure-secret 
  storageClassName: ""



